import GreenFrame.Concrete.Analysis.GreenStencilComplex

/-!
# Normalized tower TFVD: tower coordinates

First checkpoint for `ABGF-GR-003`: genuine roots, depths, tower nodes, and the
causal normalized second difference.
-/

open scoped ENNReal lp

namespace GreenFrame.Concrete

/-- A positive tower root that is not divisible by its coded positional base. -/
structure TowerRoot (r : ℕ) where
  /-- Positive value of the tower root. -/
  value : PNat
  /-- Maximality condition: one more factor of the coded base cannot be removed. -/
  not_dvd : ¬ basePNat r ∣ value

/-- Node at depth `k` in the tower generated by `root` for camera code `r`. -/
def towerNode (r : ℕ) (root : TowerRoot r) (k : ℕ) : PNat :=
  (basePNat r) ^ k * root.value

/-- A positive-depth event in one normalized positional tower. -/
structure TowerEvent where
  /-- Camera code, representing the positional base `code + 2`. -/
  code : ℕ
  /-- Maximal nondivisible root of the tower. -/
  root : TowerRoot code
  /-- Depth of the current node in the tower. -/
  depth : ℕ
  /-- Tower events always occur at positive depth. -/
  depth_pos : 0 < depth

/-- Current positive coordinate of a tower event. -/
def TowerEvent.current (t : TowerEvent) : PNat :=
  towerNode t.code t.root t.depth

/-- First ancestor of a positive-depth tower event. -/
def TowerEvent.parent (t : TowerEvent) : PNat :=
  towerNode t.code t.root (t.depth - 1)

/-- Second ancestor, used only when the event has depth at least two. -/
def TowerEvent.grandparent (t : TowerEvent) : PNat :=
  towerNode t.code t.root (t.depth - 2)

/-- Causal normalized second difference along a positional tower. -/
noncomputable def normalizedTowerTFVD (t : TowerEvent) (f : State) : ℂ :=
  f t.current -
      (((2 * carryRatio t.code : ℝ) : ℂ) * f t.parent) +
    if 2 ≤ t.depth then
      ((carryRatio t.code ^ 2 : ℝ) : ℂ) * f t.grandparent
    else
      0

/-- At depth one the unavailable second-ancestor term is absent. -/
theorem normalizedTowerTFVD_depth_one
    (t : TowerEvent) (ht : t.depth = 1) (f : State) :
    normalizedTowerTFVD t f =
      f t.current -
        (((2 * carryRatio t.code : ℝ) : ℂ) * f t.parent) := by
  simp [normalizedTowerTFVD, ht]

/-- At depth at least two the normalized tower TFVD has all three terms. -/
theorem normalizedTowerTFVD_depth_ge_two
    (t : TowerEvent) (ht : 2 ≤ t.depth) (f : State) :
    normalizedTowerTFVD t f =
      f t.current -
          (((2 * carryRatio t.code : ℝ) : ℂ) * f t.parent) +
        ((carryRatio t.code ^ 2 : ℝ) : ℂ) * f t.grandparent := by
  simp [normalizedTowerTFVD, ht]

end GreenFrame.Concrete
